"""
Energy AI Intelligence — Streamlit Dashboard
=============================================
1M1B AI for Sustainability Virtual Internship
IBM SkillsBuild & AICTE

Primary SDG  : SDG 7  — Affordable and Clean Energy
Supporting   : SDG 11 — Sustainable Cities and Communities
               SDG 12 — Responsible Consumption and Production

This dashboard displays REAL analysis results generated by the project's
completed machine-learning pipeline (Random Forest Regression).

No model is loaded or retrained here. No mock or synthetic data is used.
The source file is:  outputs/energy_analysis_results.csv

Column reference
----------------
SiteId               — building site identifier
Timestamp            — UTC observation timestamp
ForecastId           — forecast record identifier
Actual               — observed energy consumption (Wh)
Predicted            — model-predicted consumption (Wh)
Absolute_Error       — |Actual − Predicted|
Deviation_Percent    — percentage deviation from predicted value
Deviation_Direction  — "Higher than predicted" / "Lower than predicted"
Deviation_Category   — "Normal" / "Moderate deviation" / "Potential anomaly"
IsHoliday            — 1 if the period is a public holiday, else 0
Context              — "Holiday period" / "Non-holiday period"

Anomaly logic used by the ML pipeline (stored in the CSV; NOT recalculated here)
---------------------------------------------------------------------------------
MIN_CONSUMPTION = 100
Reliable    = Actual >= 100
Anomaly     = Reliable AND Deviation_Percent >= 50
"""

from pathlib import Path

import pandas as pd
import streamlit as st

# ── Path configuration ─────────────────────────────────────────────────────────
# DATA_PATH is resolved relative to this file so the app works regardless of
# the working directory when Streamlit is launched.
# To deploy, update this path to wherever the CSV is stored.
DATA_PATH = Path(__file__).resolve().parent.parent / "outputs" / "energy_analysis_results.csv"

# ── Page configuration ─────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Energy AI Intelligence",
    page_icon="⚡",
    layout="wide",
)

# ── Data loading ───────────────────────────────────────────────────────────────
@st.cache_data
def load_data(path: Path) -> pd.DataFrame:
    """
    Load the analysis results CSV once and cache it for the session.
    Only the columns needed by the dashboard are loaded to reduce memory use.
    Timestamp is parsed to datetime at load time.
    """
    usecols = [
        "SiteId", "Timestamp", "ForecastId",
        "Actual", "Predicted", "Absolute_Error",
        "Deviation_Percent", "Deviation_Direction",
        "Deviation_Category", "IsHoliday", "Context",
    ]
    df = pd.read_csv(path, usecols=usecols, parse_dates=["Timestamp"])
    return df


# ── Utilities ──────────────────────────────────────────────────────────────────
CATEGORY_COLOUR = {
    "Normal": "#2e7d32",
    "Moderate deviation": "#f9a825",
    "Potential anomaly": "#c62828",
}
DIRECTION_COLOUR = {
    "Higher than predicted": "#1565c0",
    "Lower than predicted": "#6a1b9a",
}
DEVIATION_CATEGORIES = ["Normal", "Moderate deviation", "Potential anomaly"]
CONTEXTS = ["Non-holiday period", "Holiday period"]


def badge(text: str, colour: str) -> str:
    return (
        f'<span style="background:{colour};color:#fff;padding:2px 10px;'
        f'border-radius:12px;font-size:0.78rem;font-weight:600">{text}</span>'
    )


# ── Header ─────────────────────────────────────────────────────────────────────
st.markdown(
    """
    <div style="background:#0f4c81;padding:1.2rem 1.6rem;
                border-radius:8px;margin-bottom:1rem">
        <h2 style="color:#fff;margin:0">⚡ Energy AI Intelligence</h2>
        <p style="color:#b3cde8;margin:0.3rem 0 0">
            Building Energy Consumption · Prediction &amp; Deviation Dashboard
        </p>
        <p style="color:#7aafd4;font-size:0.82rem;margin:0.2rem 0 0">
            SDG&nbsp;7 — Affordable and Clean Energy &nbsp;·&nbsp;
            SDG&nbsp;11 — Sustainable Cities &nbsp;·&nbsp;
            SDG&nbsp;12 — Responsible Consumption
        </p>
    </div>
    """,
    unsafe_allow_html=True,
)

# ── Load full dataset (cached) ─────────────────────────────────────────────────
try:
    full_df = load_data(DATA_PATH)
except FileNotFoundError:
    st.error(
        f"Data file not found: `{DATA_PATH}`\n\n"
        "Please ensure `outputs/energy_analysis_results.csv` exists in the project root."
    )
    st.stop()

site_ids = sorted(full_df["SiteId"].unique().tolist())

# ── Sidebar ────────────────────────────────────────────────────────────────────
st.sidebar.header("🏢 Site Selection")
selected_site = st.sidebar.selectbox(
    "Select a Building Site ID",
    options=site_ids,
    format_func=lambda s: f"Site {s}",
)
st.sidebar.markdown("---")
st.sidebar.markdown(
    "**ℹ️ About this dashboard**\n\n"
    "This dashboard displays the **real analysis results** generated by the "
    "project's completed machine-learning pipeline.\n\n"
    "The pipeline uses a **Random Forest Regression** model trained on the "
    "Building Sites Power Consumption dataset (Kaggle, ~6.56 M records, "
    "267 sites).\n\n"
    "A **Potential anomaly** flag means the observed consumption differs "
    "substantially from the model's expected value for that observation. "
    "It does not automatically imply energy wastage or a fault — "
    "further investigation is always recommended."
)
st.sidebar.markdown("---")
st.sidebar.caption(
    "Energy AI Intelligence\n"
    "\nBanalikha Bhattacharjya"
)

# ── Filter to selected site ────────────────────────────────────────────────────
# Filter once here; all downstream sections work on this smaller frame.
df = full_df[full_df["SiteId"] == selected_site].copy()

# Sort observations chronologically before plotting
df = df.sort_values("Timestamp").reset_index(drop=True)

total_records = len(df)

# ── KPI summary cards ──────────────────────────────────────────────────────────
st.subheader(f"📊 Site {selected_site} — Overview")

c1, c2, c3, c4, c5, c6 = st.columns(6)
c1.metric("Total Records", f"{total_records:,}")
c2.metric("Avg Actual (Wh)", f"{df['Actual'].mean():,.0f}")
c3.metric("Avg Predicted (Wh)", f"{df['Predicted'].mean():,.0f}")
c4.metric("Avg Abs Error (Wh)", f"{df['Absolute_Error'].mean():,.0f}")
c5.metric("Avg Deviation", f"{df['Deviation_Percent'].mean():.1f} %")
c6.metric(
    "Potential Anomalies",
    int((df["Deviation_Category"] == "Potential anomaly").sum()),
)

st.markdown("---")

# ── Line chart — Actual vs Predicted ──────────────────────────────────────────
st.subheader("📈 Actual vs Predicted Consumption (Wh)")
chart_df = df.set_index("Timestamp")[["Actual", "Predicted"]].sort_index()
st.line_chart(chart_df, use_container_width=True)

# ── Bar chart — Absolute Error ─────────────────────────────────────────────────
st.subheader("📉 Absolute Error per Observation (Wh)")
error_df = df.set_index("Timestamp")[["Absolute_Error"]].sort_index()
st.bar_chart(error_df, use_container_width=True)

st.markdown("---")

# ── Detailed records table ─────────────────────────────────────────────────────
st.subheader("🗂️ Detailed Records")

col_f1, col_f2 = st.columns(2)
with col_f1:
    cat_filter = st.multiselect(
        "Filter by Deviation Category",
        options=DEVIATION_CATEGORIES,
        default=DEVIATION_CATEGORIES,
    )
with col_f2:
    ctx_filter = st.multiselect(
        "Filter by Context",
        options=CONTEXTS,
        default=CONTEXTS,
    )

display_cols = [
    "Timestamp", "Actual", "Predicted",
    "Absolute_Error", "Deviation_Percent",
    "Deviation_Direction", "Deviation_Category", "Context",
]

filtered = df.loc[
    df["Deviation_Category"].isin(cat_filter) & df["Context"].isin(ctx_filter),
    display_cols,
].reset_index(drop=True)

st.dataframe(
    filtered,
    use_container_width=True,
    column_config={
        "Timestamp": st.column_config.DatetimeColumn(
            "Timestamp", format="YYYY-MM-DD HH:mm"
        ),
        "Actual": st.column_config.NumberColumn("Actual (Wh)", format="%.2f"),
        "Predicted": st.column_config.NumberColumn("Predicted (Wh)", format="%.2f"),
        "Absolute_Error": st.column_config.NumberColumn("Abs Error (Wh)", format="%.2f"),
        "Deviation_Percent": st.column_config.ProgressColumn(
            "Deviation %", min_value=0, max_value=100, format="%.1f %%"
        ),
        "Deviation_Direction": st.column_config.TextColumn("Direction"),
        "Deviation_Category": st.column_config.TextColumn("Category"),
        "Context": st.column_config.TextColumn("Context"),
    },
)
st.caption(f"Showing {len(filtered):,} of {total_records:,} records for Site {selected_site}.")

st.markdown("---")

# ── Potential anomaly section ──────────────────────────────────────────────────
st.subheader("🚨 Potential Anomaly Events")

anomalies = df[df["Deviation_Category"] == "Potential anomaly"]

if anomalies.empty:
    st.success(
        f"✅ No potential anomalies identified for Site {selected_site} "
        "in the current results."
    )
else:
    st.warning(
        f"⚠️ **{len(anomalies):,} observation(s)** were flagged as potential anomalies "
        f"for Site {selected_site}. These observations show substantial deviation "
        "from the model's expected consumption and may warrant further investigation."
    )
    # Show at most 50 rows inline to avoid overwhelming the UI for large sites
    display_limit = 50
    shown = anomalies.head(display_limit)
    for _, row in shown.iterrows():
        cat_col = CATEGORY_COLOUR.get(row["Deviation_Category"], "#555")
        dir_col = DIRECTION_COLOUR.get(row["Deviation_Direction"], "#555")
        ts_str = (
            row["Timestamp"].strftime("%Y-%m-%d %H:%M")
            if pd.notna(row["Timestamp"])
            else "—"
        )
        st.markdown(
            f"**{ts_str}** &nbsp;"
            + badge(row["Deviation_Category"], cat_col)
            + "&nbsp;"
            + badge(row["Deviation_Direction"], dir_col)
            + f"&nbsp; Deviation: **{row['Deviation_Percent']:.1f}%**"
            f" &nbsp;|&nbsp; Context: *{row['Context']}*",
            unsafe_allow_html=True,
        )
    if len(anomalies) > display_limit:
        st.caption(
            f"Showing first {display_limit} of {len(anomalies):,} potential anomaly "
            "records. Use the table above with the 'Potential anomaly' filter to see all."
        )

st.markdown("---")

# ── Interpretation ─────────────────────────────────────────────────────────────
with st.expander("ℹ️ How to interpret these results"):
    st.markdown(
        """
        **Deviation categories** are assigned by the project's ML analysis pipeline
        and are read directly from the results file. They are not recalculated here.

        | Category | Meaning |
        |---|---|
        | **Normal** | The observed consumption is within the project's normal deviation range for this observation. |
        | **Moderate deviation** | The observed consumption shows a moderate difference from the model's prediction. |
        | **Potential anomaly** | The observation was identified by the project's anomaly-analysis logic as showing a substantial deviation from expected consumption. |

        **Anomaly logic used by the ML pipeline:**
        - Only observations where `Actual ≥ 100 Wh` are considered reliable enough to flag.
        - An observation is flagged as a *Potential anomaly* when the deviation from the predicted value is **≥ 50%**.

        **Important:** A *Potential anomaly* flag means the observed consumption
        differs substantially from what the model expected for that time window.
        It does **not** automatically mean energy wastage, equipment failure, or
        any other specific cause. Each flagged observation should be investigated
        in the context of the building's actual operating conditions.

        **Holiday context** is included because consumption patterns on public
        holidays or weekends often differ from regular working days, which is
        relevant when interpreting an unexpected deviation.
        """
    )

# ── Footer ─────────────────────────────────────────────────────────────────────
st.markdown(
    """
    <div style="text-align:center;color:#888;font-size:0.8rem;
                padding-top:0.5rem;border-top:1px solid #e5e7eb;margin-top:0.5rem">
        Energy AI Intelligence &nbsp;·&nbsp;
        Banalikha Bhattacharjya <br>
        SDG&nbsp;7 — Affordable and Clean Energy &nbsp;·&nbsp;
        SDG&nbsp;11 — Sustainable Cities &nbsp;·&nbsp;
        SDG&nbsp;12 — Responsible Consumption
    </div>
    """,
    unsafe_allow_html=True,
)
